
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class MainInterface extends javax.swing.JFrame {
    //Icons for Heart and Cart
    private Icon heartIconActive;
    private Icon defaultHeart;
    
    private Icon cartActive;
    private Icon defaultCart;
    
    CardLayout cardLayout;
    public MainInterface() {
        initComponents();
        
        cardLayout = (CardLayout)(panelCards.getLayout());
        
        //heart path
        heartIconActive = new ImageIcon("Assets\\\\heart_active.png");
        defaultHeart = new ImageIcon("Assets\\\\heart.png");
        
        //cart path
        cartActive = new ImageIcon("Assets\\\\cart_active.png");
        defaultCart = new ImageIcon("Assets\\\\cart.png");
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Navbar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        profileTab = new javax.swing.JButton();
        cartTab = new javax.swing.JButton();
        favoriteTab = new javax.swing.JButton();
        homeTab = new javax.swing.JButton();
        petTab = new javax.swing.JButton();
        settingTab = new javax.swing.JButton();
        panelCards = new javax.swing.JPanel();
        panelCard1 = new javax.swing.JPanel();
        panelCard2 = new javax.swing.JPanel();
        panelCard3 = new javax.swing.JPanel();
        panelCard4 = new javax.swing.JPanel();
        panelCard5 = new javax.swing.JPanel();
        panelCard6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSplitPane1.setEnabled(false);

        Navbar.setBackground(new java.awt.Color(40, 40, 40));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Animalia\\Assets\\logo\\Animalia Logo.png")); // NOI18N

        profileTab.setBackground(new java.awt.Color(40, 40, 40));
        profileTab.setForeground(new java.awt.Color(40, 40, 40));
        profileTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Animalia\\Assets\\profile.png")); // NOI18N
        profileTab.setToolTipText("Profile");
        profileTab.setBorder(null);
        profileTab.setBorderPainted(false);
        profileTab.setContentAreaFilled(false);
        profileTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileTabActionPerformed(evt);
            }
        });

        cartTab.setBackground(new java.awt.Color(40, 40, 40));
        cartTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Animalia\\Assets\\cart.png")); // NOI18N
        cartTab.setToolTipText("Add To Cart");
        cartTab.setBorder(null);
        cartTab.setContentAreaFilled(false);
        cartTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cartTabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cartTabFocusLost(evt);
            }
        });
        cartTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartTabActionPerformed(evt);
            }
        });

        favoriteTab.setBackground(new java.awt.Color(40, 40, 40));
        favoriteTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Animalia\\Assets\\heart.png")); // NOI18N
        favoriteTab.setToolTipText("Favorites");
        favoriteTab.setBorder(null);
        favoriteTab.setContentAreaFilled(false);
        favoriteTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                favoriteTabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                favoriteTabFocusLost(evt);
            }
        });
        favoriteTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoriteTabActionPerformed(evt);
            }
        });

        homeTab.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        homeTab.setForeground(new java.awt.Color(139, 139, 139));
        homeTab.setText("Home");
        homeTab.setBorder(null);
        homeTab.setContentAreaFilled(false);
        homeTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeTabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homeTabFocusLost(evt);
            }
        });
        homeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeTabActionPerformed(evt);
            }
        });

        petTab.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        petTab.setForeground(new java.awt.Color(139, 139, 139));
        petTab.setText("Pets");
        petTab.setBorder(null);
        petTab.setContentAreaFilled(false);
        petTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                petTabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                petTabFocusLost(evt);
            }
        });
        petTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petTabActionPerformed(evt);
            }
        });

        settingTab.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        settingTab.setForeground(new java.awt.Color(139, 139, 139));
        settingTab.setText("Settings");
        settingTab.setBorder(null);
        settingTab.setContentAreaFilled(false);
        settingTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                settingTabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                settingTabFocusLost(evt);
            }
        });
        settingTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(76, 76, 76)
                .addComponent(homeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(petTab, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingTab, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(favoriteTab)
                .addGap(29, 29, 29)
                .addComponent(cartTab)
                .addGap(36, 36, 36)
                .addComponent(profileTab)
                .addGap(15, 15, 15))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(favoriteTab)
                            .addComponent(cartTab))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                        .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NavbarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(homeTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(petTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(settingTab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(logo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(profileTab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jSplitPane1.setLeftComponent(Navbar);

        panelCards.setBackground(new java.awt.Color(18, 18, 18));
        panelCards.setForeground(new java.awt.Color(204, 204, 204));
        panelCards.setLayout(new java.awt.CardLayout());

        panelCard1.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout panelCard1Layout = new javax.swing.GroupLayout(panelCard1);
        panelCard1.setLayout(panelCard1Layout);
        panelCard1Layout.setHorizontalGroup(
            panelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        panelCard1Layout.setVerticalGroup(
            panelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        panelCards.add(panelCard1, "card1");

        panelCard2.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout panelCard2Layout = new javax.swing.GroupLayout(panelCard2);
        panelCard2.setLayout(panelCard2Layout);
        panelCard2Layout.setHorizontalGroup(
            panelCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        panelCard2Layout.setVerticalGroup(
            panelCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        panelCards.add(panelCard2, "card2");

        panelCard3.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout panelCard3Layout = new javax.swing.GroupLayout(panelCard3);
        panelCard3.setLayout(panelCard3Layout);
        panelCard3Layout.setHorizontalGroup(
            panelCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        panelCard3Layout.setVerticalGroup(
            panelCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        panelCards.add(panelCard3, "card3");

        javax.swing.GroupLayout panelCard4Layout = new javax.swing.GroupLayout(panelCard4);
        panelCard4.setLayout(panelCard4Layout);
        panelCard4Layout.setHorizontalGroup(
            panelCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        panelCard4Layout.setVerticalGroup(
            panelCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        panelCards.add(panelCard4, "card4");

        panelCard5.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout panelCard5Layout = new javax.swing.GroupLayout(panelCard5);
        panelCard5.setLayout(panelCard5Layout);
        panelCard5Layout.setHorizontalGroup(
            panelCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        panelCard5Layout.setVerticalGroup(
            panelCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        panelCards.add(panelCard5, "card5");

        panelCard6.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout panelCard6Layout = new javax.swing.GroupLayout(panelCard6);
        panelCard6.setLayout(panelCard6Layout);
        panelCard6Layout.setHorizontalGroup(
            panelCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        panelCard6Layout.setVerticalGroup(
            panelCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        panelCards.add(panelCard6, "card6");

        jSplitPane1.setRightComponent(panelCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        setSize(new java.awt.Dimension(1198, 783));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileTabActionPerformed
        cardLayout.show(panelCards, "card4");
    }//GEN-LAST:event_profileTabActionPerformed

    private void settingTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingTabActionPerformed
        cardLayout.show(panelCards, "card3");
    }//GEN-LAST:event_settingTabActionPerformed

    private void homeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeTabActionPerformed
        cardLayout.show(panelCards, "card1");
    }//GEN-LAST:event_homeTabActionPerformed

    private void petTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petTabActionPerformed
        cardLayout.show(panelCards, "card2");
    }//GEN-LAST:event_petTabActionPerformed

    private void favoriteTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoriteTabActionPerformed
        cardLayout.show(panelCards, "card6");
    }//GEN-LAST:event_favoriteTabActionPerformed

    private void homeTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeTabFocusGained
        
        homeTab.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED),
                    homeTab.getBorder()
                ));
 
    }//GEN-LAST:event_homeTabFocusGained

    private void homeTabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeTabFocusLost
         homeTab.setBorder(UIManager.getBorder("Button.border"));
    }//GEN-LAST:event_homeTabFocusLost

    
    private void petTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_petTabFocusGained
        petTab.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED),
                petTab.getBorder()
        ));
    }//GEN-LAST:event_petTabFocusGained

    private void petTabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_petTabFocusLost
        petTab.setBorder(UIManager.getBorder("Button.border"));
    }//GEN-LAST:event_petTabFocusLost

    private void settingTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_settingTabFocusGained
        settingTab.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED),
                settingTab.getBorder()
        ));
    }//GEN-LAST:event_settingTabFocusGained

    private void settingTabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_settingTabFocusLost
        settingTab.setBorder(UIManager.getBorder("Button.border"));
    }//GEN-LAST:event_settingTabFocusLost

    private void cartTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartTabActionPerformed
        cardLayout.show(panelCards, "card5");
    }//GEN-LAST:event_cartTabActionPerformed

    private void favoriteTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_favoriteTabFocusGained
        favoriteTab.setIcon(heartIconActive);
    }//GEN-LAST:event_favoriteTabFocusGained

    private void favoriteTabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_favoriteTabFocusLost
        favoriteTab.setIcon(defaultHeart);
    }//GEN-LAST:event_favoriteTabFocusLost

    private void cartTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cartTabFocusGained
        cartTab.setIcon(cartActive);
    }//GEN-LAST:event_cartTabFocusGained

    private void cartTabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cartTabFocusLost
        cartTab.setIcon(defaultCart);
    }//GEN-LAST:event_cartTabFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Navbar;
    private javax.swing.JButton cartTab;
    private javax.swing.JButton favoriteTab;
    private javax.swing.JButton homeTab;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelCard1;
    private javax.swing.JPanel panelCard2;
    private javax.swing.JPanel panelCard3;
    private javax.swing.JPanel panelCard4;
    private javax.swing.JPanel panelCard5;
    private javax.swing.JPanel panelCard6;
    private javax.swing.JPanel panelCards;
    private javax.swing.JButton petTab;
    private javax.swing.JButton profileTab;
    private javax.swing.JButton settingTab;
    // End of variables declaration//GEN-END:variables
}
